name: Deploy the Backend
on:
  push:
    branches: [main]
    paths:
      - 'DevOps/Docker/TodoApp/apps/backend/**'
      - 'DevOps/Docker/TodoApp/packages/**'     
      - 'DevOps/Docker/TodoApp/docker/Dockerfile.backend'
      - 'DevOps/Docker/TodoApp/package.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./DevOps/Docker/TodoApp/
          file: ./DevOps/Docker/TodoApp/docker/Dockerfile.backend
          push: true
          tags: ronaksingh2006/todo-app-backend:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}  
      
      - name: Deploy to VM
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@65.2.180.247 << 'EOF'
            docker pull ronaksingh2006/todo-app-backend:${{ github.sha }}
            docker stop user_backend || true
            docker rm user_backend || true
            docker run --name user_backend -d \
              -p 3001:3001 \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              ronaksingh2006/todo-app-backend:${{ github.sha }}
          EOF